title: CHENYXBlog
description: 写一些杂七杂八的记录博客
#网站的根地址
baseurl: "https://github.com/CHENYXGitHub"
url: "/CHENYXBlog"

author:
  name: CHENYX
  github_username: CHENYXGitHub

defaults:
  #把value应用给scope路径里的所有文件。因为路径被设置为空字符串，
  #所以它将会应用到你项目里的全部文件。你可能不想给项目在每个文件
  #都设置一个布局，例如CSS文件，那么你可以在scope下制定type的值。
  #现在是只会给类型是posts的文件设置默认布局。你可以其他的类型，如：
  #pages,posts,drafts或者其他你站点中的集合
   -
    scope:
      path: '' #一个空的字符串代表项目中所有的文件
      type: 'posts' #以前的'post'，在Jekyll 2.2里
    values:
      layout: 'post'

#jekyll写入文件的路径
destination: _site
#每页该展示多少项目
paginate: 10
#如果你需要让发布的博客的URL地址不同于默认值/year/month/day/title.html那么
#可以设置这个变量，然后变量值就会作为最终的URL地址
permalink: /:year/:title/
markdown: kramdown
#代码高亮显示
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM             #使用Github Flavored Markdown
  hard_wrap: false       #不使用<br>替换新行
plugins: ['jekyll-paginate']
#转换时排除某些文件、文件夹
exclude: ['Gemfile','Gemfile.lock']